### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by arsaces7** [android-police/datetime-now-button#1]
its not working with wp 5 please update it

**Comment by archon810** [comment]
It's working - we're using it with the latest WordPress.

**Comment by arsaces7** [comment]
> It's working - we're using it with the latest WordPress.

i just installed plugin and can't see the button , is there anything special to do?

**Comment by archon810** [comment]
Not that I know of. We just forked the code, if you need to file a bug, go to the original repo.
